### ISSUE TITLE
[Feature]: Migration to slash commands

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [commclassroom/classroom-monitor-bot#102]

**Comment by DhansAL** [comment]
I'd like to try this one ^_^

**Comment by Panquesito7** [comment]
> I'd like to try this one ^_^

Feel free to work on it! Let us know if you need any help. :)

**Comment by DhansAL** [comment]
this requires discord v13. I'll make the changes accordingly.

**Comment by DhansAL** [comment]
this issue has been resolved
