### ISSUE TITLE
[Bug]: Bot not capturing edtech startups

### ISSUE THREAD

**Issue by kkhitesh** [commclassroom/classroom-monitor-bot#106]

**Comment by genzyy** [comment]
I am up for this if this issue is needed to be fixed.

**Comment by Panquesito7** [comment]
> I am up for this if this issue is needed to be fixed.

Yes, I think this hasn't been fixed yet. 😅

**Comment by genzyy** [comment]
> > I am up for this if this issue is needed to be fixed.
> 
> Yes, I think this hasn't been fixed yet. sweat_smile

Sure, I will make a PR for fixing this.
