### ISSUE TITLE
[BUG] Add `remain` to the whitelist

### ISSUE THREAD

**Issue by Panquesito7** [commclassroom/classroom-monitor-bot#132]
### Describe the bug

`remain` is something we should add to the whitelist, this is not a problem. 🙂

*If you already forked this repository, skip to step 3*

1. Fork the repository [**here**](https://github.com/commclassroom/classroom-monitor-bot/fork)
2. Go to the [`config.json`](https://github.com/commclassroom/classroom-monitor-bot/blob/main/config.json) file (make sure you're in your fork!).
3. Change the line 47 to the following content:

```json
            "special",
            "remain"
```

4. Time to make your PR! Once you make it, the maintainers will review it and merge it if all is good. 🚀 <br> Do let us know if you need any help! Feel free to make a comment here or ask via our [**Discord**](https://discord.gg/commclassroom) community. 🙂

**Comment by venusaim23** [comment]
Hey @Panquesito7 I'd like to work on this issue and get familiar with solving my first issue. Can you assign it to me?
