### ISSUE TITLE
[Chore] Remove the error reply

### ISSUE THREAD

**Issue by SiddhantKhisty** [commclassroom/classroom-monitor-bot#135]
### What would you like to share?

CM gives a reply where it says it cannot understand certain languages. You must remove this line
![Screenshot_20211209-223454_Discord](https://user-images.githubusercontent.com/73576223/145442979-7c4154e7-319e-4f37-9970-7f59406daa3b.jpg)

### Would you like to work on this issue?

- [ ] Yes, I want to work on this issue!

**Comment by unnikrishnan2002** [comment]
Can I work on this @SiddhantKhisty ?

**Comment by SiddhantKhisty** [comment]
@unnikrishnan2002  go ahead
