### ISSUE TITLE
[BUG] Add "UK" to whitelist

### ISSUE THREAD

**Issue by unnikrishnan2002** [commclassroom/classroom-monitor-bot#151]
### Describe the bug

Since it represents a place and it doesn't convey any wrong meaning to anyone it should be removed from blacklist.

### Expected Behavior

Don't give warnings for place names

**Comment by unnikrishnan2002** [comment]
Can I try that ?

**Comment by Panquesito7** [comment]
> Can I try that ?

Of course! Feel free to work on it! Let us know if you need any help! 😃

**Comment by unnikrishnan2002** [comment]
Hey @Panquesito7 Can you please point our the file location where I need to make the changes?

**Comment by unnikrishnan2002** [comment]
Ohh ,okay I have to add it in config.json right?
