### ISSUE TITLE
[BUG] Trigger for Whitespace

### ISSUE THREAD

**Issue by SiddhantKhisty** [commclassroom/classroom-monitor-bot#154]
### Describe the bug

The bot triggers a warning for the word `whitespace`

Add the word to the whitelist 

### To Reproduce

Type `whitespace` with the bot in your server

### Screenshot/ Video

![Screenshot_20220103-213843_Discord](https://user-images.githubusercontent.com/73576223/147953268-0ce1dcc3-e5cf-4376-8347-fbc5680e175f.jpg)

**Comment by Ameen-Here** [comment]
Can I take up this issue?
I would love to sort it out.
