### ISSUE TITLE
[BUG] Website not deploying

### ISSUE THREAD

**Issue by Panquesito7** [commclassroom/classroom-monitor-bot#162]
### Describe the bug

Looks like the website's not deplyoying anymore.

CC: @kaiwalyakoparkar, @siddhant-khisty.

**Comment by siddhant-khisty** [comment]
Hey @Panquesito7, we have rebranded to wemakedevs. The website can be found at     
https://wemakedevs.org/

**Comment by Panquesito7** [comment]
Ah, nice, working now https://wemakedevs.github.io/classroom-monitor-bot/#/
A few hours ago it wasn't working for some reason. 🤔
